.PHONY: check

check:
	make -C prj-name                     check
	make -C bak-dest                     check
	make -C bak-info                     check
	make -C autoderived-options          check
	make -C source                       check
	make -C rsync-usage                  check
	make -C gen-backup-name              check
	make -C create-new-backup            check
	make -C locking                      check
	make -C update                       check
	make -C clean                        check
	make -C list                         check
	make -C find                         check
	make -C tag                          check
	make -C remove-project               check
